### PR TITLE
Update to latest deps.

### PR DESCRIPTION
**Pull request by kennyp**
Links
-----
- [Trello](https://trello.com/c/DGJEITVZ)

### CODE REVIEW

**Comment by kennyp** [comment]
[Upgrade vault-tools to Ruby 2.5.3](https://trello.com/c/DGJEITVZ/141-upgrade-vault-tools-to-ruby-253)

**Comment by maxbeizer** [comment]
@kennyp looks like CI is failing to due bundler changes

**Comment by maxbeizer** [comment]
RIP zipkin, my nemesis

**Comment by kennyp** [comment]
@maxbeizer it's failing because I need to re-bundle after deploying `vault-test-tools`.

**Comment by maxbeizer** [comment]
LGTM once that gets resolved

**Pull request merged**
